# # #
# dockerized nekoserv's disabled services
#

version: '3.6'

networks:
  private0:

services:

  main-services:
    image: hello-world
    container_name: main-services-disabled
    depends_on:
      - couchpotato
      - headphones
      - nginx-static-index
      - rutorrent
      - rutorrent-fpm
      - sickchill


  couchpotato:
    build:
      context: dockerfiles/couchpotato
      args:
        UID: 1000
        GID: 1000
    container_name: couchpotato
    networks:
      - private0
    expose:
      - "5050"
    restart: unless-stopped
    environment:
      - TZ=$ENV_TIMEZONE
    tmpfs:
      - /tmp
    volumes:
      - ~/docker-data/couchpotato/data:/home/couchpotato/data
      - ~/Downloads/incomplete:/home/incomplete
      - ~/Downloads/postprocessing:/home/postprocessing
      - /mnt/nas/FILMS:/home/couchpotato/dl
    read_only: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.couchpotato.rule=Host(`$ENV_DOMAIN`) && PathPrefix(`/couchpotato`)"
      - "traefik.http.routers.couchpotato.tls=true"
      - "traefik.http.routers.couchpotato.middlewares=global-auth@file"
      - "traefik.http.routers.couchpotato.tls.certresolver=default-ssl"


  headphones:
    build:
      context: dockerfiles/headphones
      args:
        UID: 1000
        GID: 1000
    container_name: headphones
    networks:
      - private0
    expose:
      - "8181"
    restart: unless-stopped
    environment:
      - TZ=$ENV_TIMEZONE
    tmpfs:
      - /tmp
    volumes:
      - ~/docker-data/headphones/data:/home/headphones/data
      - ~/Downloads/incomplete:/home/incomplete
      - ~/Downloads/postprocessing:/home/postprocessing
      - /mnt/nas/musics:/home/headphones/dl
    read_only: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.headphones.rule=Host(`$ENV_DOMAIN`) && PathPrefix(`/headphones`)"
      - "traefik.http.routers.headphones.tls=true"
      - "traefik.http.routers.headphones.middlewares=global-auth@file"
      - "traefik.http.routers.headphones.tls.certresolver=default-ssl"


  nginx-static-index:
    build:
      context: dockerfiles/nginx-static-index
      args:
        UID: 1000
        GID: 1000
    container_name: nginx-static-index
    networks:
      - private0
    expose:
      - "18080"
    restart: unless-stopped
    environment:
      - TZ=$ENV_TIMEZONE
    tmpfs:
      - /tmp
    volumes:
      - ~/docker-data/nginx-static-index/static:/home/nginx/static
    read_only: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-static-index.rule=Host(`$ENV_DOMAIN`) && PathPrefix(`/`)"
      - "traefik.http.routers.nginx-static-index.tls=true"
      - "traefik.http.routers.nginx-static-index.middlewares=global-auth@file"
      - "traefik.http.routers.nginx-static-index.tls.certresolver=default-ssl"


  rutorrent:
    build:
      context: dockerfiles/rutorrent
      args:
        UID: 1000
        GID: 1000
        CONTAINER_NAME: openvpn-client
        RTORRENT_PORT: 5001
    container_name: rutorrent
    networks:
      - private0
    expose:
      - "18080"
    restart: unless-stopped
    environment:
      - TZ=$ENV_TIMEZONE
    tmpfs:
      - /tmp
    volumes:
      - ~/docker-data/rutorrent:/home/rutorrent/
    read_only: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rutorrent.rule=Host(`$ENV_DOMAIN`) && PathPrefix(`/rutorrent`)"
      - "traefik.http.routers.rutorrent.tls=true"
      - "traefik.http.routers.rutorrent.middlewares=global-auth@file"
      - "traefik.http.routers.rutorrent.tls.certresolver=default-ssl"


  rutorrent-fpm:
    build:
      context: dockerfiles/rutorrent-fpm
      args:
        UID: 1000
        GID: 1000
    container_name: rutorrent-fpm
    networks:
      - private0
    expose:
      - "9000"
    restart: unless-stopped
    environment:
      - TZ=$ENV_TIMEZONE
    tmpfs:
      - /tmp
    volumes:
      - ~/docker-data/rutorrent:/home/rutorrent/
    read_only: true


  sickchill:
    build:
      context: dockerfiles/sickchill
      args:
        UID: 1000
        GID: 1000
    container_name: sickchill
    networks:
      - private0
    expose:
      - "8081"
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
    volumes:
      - ~/docker-data/sickchill/data:/home/sickchill/data
      - ~/Downloads/complete/SERIES:/home/sickchill/dl
      - ~/Downloads/postprocessing:/home/postprocessing
      - ~/Downloads/incomplete:/home/incomplete
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sickchill.rule=Host(`$DOMAIN`) && PathPrefix(`/sickchill`)"
      - "traefik.http.routers.sickchill.tls=true"
      - "traefik.http.routers.sickchill.middlewares=global-auth@file"
      - "traefik.http.routers.sickchill.tls.certresolver=default-ssl"

  transmission:
    build:
      context: dockerfiles/transmission
      args:
        UID: 1000
        GID: 1000
    container_name: transmission
    restart: unless-stopped
    depends_on:
      - openvpn-client
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    network_mode: service:openvpn-client
    environment:
      - TZ=$ENV_TIMEZONE
    tmpfs:
      - /tmp
    volumes:
      - ~/docker-data/transmission/:/home/tbt/.config/transmission-daemon/
      - ~/docker-data/nzbToMedia:/home/rtorrent/nzbToMedia
      - /mnt/nas/share:/home/rtorrent/share
      - ~/docker-data/dl/incomplete/torrent:/home/incomplete
      - ~/docker-data/dl/postprocessing:/home/postprocessing
    stdin_open: true
    tty: true
